// Importing roboto font from google
import { Roboto } from 'next/font/google';

// Importing fontawosomes
// import { config } from '@fortawesome/fontawesome-svg-core'
// import '@fortawesome/fontawesome-svg-core/styles.css'
// config.autoAddCss = false

// Importing global css here
import "./globals.css";


const getRoboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`${getRoboto.className} antialiased`}>
        {children}
        </body>
        </html>
    );
}
